---
# all those values can be reconfigured over the terminal
wifi:
  ssid: none
  pass: none 

ifconfig:
  static: 0
  addr: 10.10.3.60
  gateway: 10.10.1.1
  netmask: 255.255.0.0
  dns: 10.10.1.1

# enabling can only be configured during build time, port when its running
tcp_server:
  enable: true
  port: 9040


# enabling can only be configured during build time, port when its running
web_server:
  enable: true
  port: 80

# serial console can only be enabled/disabled during build time
# if the console is disabled, settings can only be made in this file
console:
  enable: true
  # null bytes need to be double escaped here
  prompt: "\\033[38;5;2mmicronova-controller# \\033[0;10m"