---
# all those values can be reconfigured over the terminal
wifi:
  ssid: none
  pass: none 

ifconfig:
  static: 0
  addr: 10.10.3.60
  gateway: 10.10.1.1
  netmask: 255.255.0.0
  dns: 10.10.1.1

tcp_server_port: 9040


# enabling & configuring web server only supported during build time
web_server:
  enable: true
  port: 80